from langchain_core.messages import HumanMessage

from app.services.llm import llm
from app.state import SDLCState
from app.prompts.product_owner import PRODUCT_OWNER_PROMPT
from app.schemas.artifacts import ProductOwnerArtifact

def product_owner_nodes(state: SDLCState):

    prompt = PRODUCT_OWNER_PROMPT.format(
        requirements=state["requirements"]
    )

    response = llm.invoke(
        [HumanMessage(content=prompt)]
    )

    artifact = ProductOwnerArtifact(
        stage="product Owner",
        stauts="completed",
        summary="Generated project planning artifacts.",
        recommendation="Proceed to Arctecture Design.",
        confidence=0.95,
        
        project_vision="Generated by AI",

        user_stories=[],

        acceptance_criteria=[],

        risks=[]
    )    

    state["product_owner_artifact"] = artifact

    state["history"].append(
        "Product Owner Completed."
    )

    state["current_stage"] = "Arcitecture"

    return state
